[[main]]
name = "papers"
pageRef = "papers"
identifier = "3vxdSNuqxZ"
weight = 1

[[main]]
name = "type"
pageRef = "type"
identifier = "3zAQoPi1Z8"
weight = 2

[[main]]
name = "categories"
pageRef = "categories"
identifier = "d9R1G6BojF"
weight = 3

[[main]]
name = "benchmarks"
pageRef = "benchmarks"
identifier = "Zgx9ovTuNC"
weight = 4

[[footer]]
none = "none"
